leroy-merlin-br/garden

- CONTRIBUTING.md
- contributing.md
> Add CONTRIBUTING.md

- docs/css/base/colors.css
- docs/css/main.css
- docs/css/molecules/sidebar.css
- docs/layout/_partials/sidebar.jade
- docs/layout/page.jade
> feat(sidebar): add sidebar style

- README.md
> docs(readme): add initial readme file

- CONTRIBUTING.md
> docs(contributing): change texts

- docs/css/atoms/breakpoints.css
- docs/css/atoms/container.css
- docs/css/organisms/docs.css
- docs/css/organisms/example.css
- docs/grid.md
> feat(grid): add grid information

- docs/button.md
- docs/colors.md
- docs/css/molecules/palette.css
- docs/css/organisms/banner.css
- docs/css/organisms/docs.css
- docs/css/organisms/example.css
- docs/layout/index.jade
- docs/layout/page.jade
- gulp/postcss-processors.js
- metalsmith.js
- package.json
- src/css/atoms/button.css
- src/css/defaults.json
- src/css/garden.css
> feat(buttons): add buttons atom

- docs/button.md
- docs/colors.md
- docs/grid.md
- docs/typography.md
- metalsmith.js
> feat(sidebar): add menu priority

- docs/button.md
- docs/css/organisms/docs.css
- docs/typography.md
> feat(docs): change code highlight and code preview

- docs/css/organisms/docs.css
- docs/form.md
- src/css/atoms/form/helper.css
- src/css/atoms/form/input.css
- src/css/atoms/form/label.css
- src/css/atoms/form/select.css
- src/css/garden.css
> feat(form): form atoms

- .coveralls.yml
- README.md
- package.json
> feat(coveralls): add coveralls integration

- docs/about.md
- docs/layout/_partials/header.jade
- docs/layout/index.jade
- docs/layout/page.jade
> feat(about): add about page

- docs/getting-started.md
- docs/layout/_partials/header.jade
- docs/scaffolding.md
> docs(scaffolding): add scaffolding page

- .travis.yml
- gulp/lint-css.js
- gulp/lint-js.js
- gulpfile.babel.js
- package.json
> chore(lint): Move css & js linters to gulp

- package.json
- src/css/atoms/badge.css
- src/css/atoms/border.css
- src/css/atoms/button.css
- src/css/atoms/modal.css
- src/css/atoms/modal/content.css
- src/css/atoms/typography.css
- src/css/molecules/input-button.css
- src/css/utils/mixins.css
Modal: when using form component or button inside modal, it cause
a blurry effect in everything inside it. The problem is when using translate to center modal.
Button: change box-shadow animation, using the same approach applied in thumbnail
> chore(button/modal): fix problems

- src/css/atoms/button.css
Use `@each` instead create more classes
> refactor(button): refactor code to use @each

- package.json
chore(package.json): Move jump.js from devDeps to deps on package.json
Jump.js should be listed as a true dependency instead of a dev dependency.
> chore(package.json): Move jump.js from devDeps to deps on package.json

- docs/css/scaffolding.md
- src/css/atoms/modal.css
- src/css/atoms/modal/content.css
- src/css/defaults.json
- Add `z-index` variables for (re)use.
- Update modal `z-index` to use `$index-foremost`
- Remove unnecessary `z-index` from `.modal-content`
> feat(z-index): add new global vars

- .stylelintrc
- package.json
- src/css/atoms/button.css
And also updated stylelint to 7.0.3.
> fix(button): missing hover

- docs/css/glyphs.md
- src/glyphs/chat-balloon.svg
> feat(glyphs): add chat-balloon icon

- docs/css/colors.md
- docs/styles/molecules/palette.css
- src/css/defaults.json
Adds a new color variable `$color-black` with the value `#000000`.
> feat(color): add color-black

- docs/css/pricetag.md
- docs/css/thumbnail.md
> fix(price-tag): less info in according to the guideline specs

- docs/css/pagination.md
- docs/styles/organisms/example.css
- src/css/atoms/pagination/arrows.css
- src/css/atoms/pagination/item.css
- src/css/garden.css
This create our default style paginate.
> feat(pagination): create pagination section

- src/css/atoms/form/select.css
- src/css/molecules/field.css
This revert feature #179.
It's not working as we planned, so for while this will "fix" the problem
> Revert "feat(select): Open select option on label click"

- docs/css/button.md
- src/css/atoms/button.css
Add the style to button full. 
Documentation:
> feat(button): Add button full style

- Dockerfile
- README.md
- docker-compose.yml
- tasks/server.js
Add configuration files for a docker container as an alternative method to run the project locally.
> feat(docker): setup docker container

- src/css/atoms/tooltip.css
- src/js/components/tooltip.js
Currently, our tooltip component doesn't enable us to give some options to modify the component's behavior (like placement). This PR updates the component to make it work.
> feat(tooltip): Allow options to be passed to the Tooltip component

- docs/js/emitter.md
- docs/js/form.md
- docs/layout/_partials/header.jade
Adjust sentences and structure for text paragraphs.
> docs(js-form): Improve documentation for Form component

- docs/css/colors.md
- docs/css/typography.md
- docs/js/emitter.md
- src/css/atoms/text/heading.css
- src/css/atoms/text/link.css
Rephrase sentences and adjust structure for several sections.
> docs(typography): Improve documentation for Typography page

- docs/components/css-utilities.md
Rephrase several sentences and HTML example blocks.
> docs(utils-css): Improve docs for CSS Utils page

- docs/components/css-form.md
- docs/components/js-form.md
Readjust the CSS Form documentation at docs components
> fix(docs): Readjust CSS Form to docs

- docs/getting-started.md
Change structure for several sections, rephrase sentences, and correct grammar issues.
> docs(getting-started): Adjust docs for Getting Started page

- docs/components/scaffolding.md
Change structure for several blocks and rephrase sentences.
> docs(scaffolding): Improve documentation for Scaffolding page

- docs/components/glyphs.md
Change structure of blocks and rephrase sentences.
> docs(glyphs): Improve documentation for Glyph component

- docs/components/colors.md
Change structure for blocks and rephrase sentences.
> docs(colors): Improve documentation for Colors page

- docs/components/pagination.md
Adjust sentences and structure for description block.
> docs(pagination): Improve documentation for Pagination component page

- docs/components/css-notifications.md
Rephrase sentences and adjust HTML example code.
> docs(notification): Improve docs for the Notification CSS component

- docs/components/thumbnail.md
> docs(thumbnail): Improve docs for Thumbnail component page

- docs/styles/organisms/docs.css
> fix(docs): stylelint warnings

- docs/components/badges.md
Add component description and rephrase sentences.
> docs(badges): Improve docs for Badge component page

- docs/components/panel.md
Rephrase sentences and adjust structure for HTML example snippets.
> docs(panel): Improve docs for Panel component page

- docs/components/modal.md
Rephrase sentences, change structure for several blocks, and add a summary.
> docs(modal): Improve docs for Modal component page

- docs/components/collapse.md
Rephrase sentences, change structure for several blocks, and add a summary.
> docs(collapse): Improve docs for Collapse component page

- docs/components/lazy-load.md
Rephrase sentences and add a summary
> docs(lazy-load): Improve docs for Lazy Load component page

- docs/components/alert.md
Rephrase sentences and add page summary.
> docs(alert): Improve docs for Alert component page

- docs/components/validation.md
> docs(validation): Improve docs for Validation component page

- docs/components/tooltip.md
> docs(tooltip): Improve docs for Tooltip component page

- docs/components/js-utilities.md
- docs/layout/page.jade
> docs(utils-js): Improve docs for Util components page

- package.json
- src/js/utils/scroll.js
- test/utils/scroll.spec.js
This PR should solve #231 problem
> feat(jump.js): update to v1.0.2

- .stylelintrc
This reverts commit 204be1ae4f9a94fa13d49e865309cd9086bc177a.
> revert(stylelint): Update syntax for stylelint rule

- docs/components/modal.md
- docs/layout/page.jade
Add example for  history modal in documentation.
> docs(modal): add example for history modal in docs

- package.json
> chore(package): update karma-html2js-preprocessor to version 1.1.0

- .babelrc
- package.json
https://babeljs.io/docs/plugins/transform-object-rest-spread/
> feat(babelrc): update object assign to object spread

- package.json
- webpack.config.js
- webpack.production.config.js
This is to substitute `$.addClass`, `$.removeClass` and `$.toggleClass`.
[classList docs](https://developer.mozilla.org/pt-BR/docs/Web/API/Element/classList)
> feat(classList): add classlist polyfil

- src/js/utils/trigger-event.js
- test/utils/trigger-event.spec.js
This helper was based on [this one](https://plainjs.com/javascript/events/trigger-an-event-11/) and refactored for our own development environment.
> feat(trigger-event): create helper for triggering events

- .eslintrc
- src/js/utils/dom-parser.js
- test/utils/dom-parser.spec.js
Create a dom parser helper to replace a JQuery method that create a DOM element from string parameter.
> feat(utils): create dom parser

- .babelrc
- package.json
and target browsers versions to preset.
http://babeljs.io/env
> feat(babel): use babel-preset-env instead of babel-preset-2015

- package.json
Remove old version 0.50.0 to 0.51.0
> hotfix(version): replace version
