- gulp/build-css.js
- gulp/docs-css.js
- gulp/error-handler.js
- package.json
As gulp-plumber was not working properly with gulp-postcss, we decided
to use `.on('errror')` to handle postCSS build errors.
> feat(gulp): add error handler

- src/js/components/form.js
- src/js/components/lazy-load.js
- src/js/components/validation/confirm.js
remove `options` from `constructor` and call `$.extend` directly in `this._options`.
> chore(components): minor changes

- docs/css/form.md
I've added a docs about using a glyph in `.addon` field.
> feat(form): add example on docs about glyphs on addon field

- docs/css/table.md
- docs/styles/organisms/docs.css
- src/css/atoms/table.css
- src/css/garden.css
This PR adds a table css component to garden. The component is pretty simple, it's just some base styles for a table element, with a variant class `table-zebra` to display a zebra stripes styled table.
> feat(table): add table css component

- docs/css/table.md
- src/css/atoms/table.css
This PR adds a new variant to the table component. A bordered table.
> feat(table): add bordered table

- src/js/components/modal.js
- test/components/modal.spec.js
This PR adds a typical modal behavior: when a click is done outside the modal window, it is expected the modal to be closed.
> feat(modal): hide modal when a click is done outside its content

- docs/css/button.md
- src/css/atoms/button-hollow.css
- src/css/atoms/button.css
- src/css/garden.css
- src/css/utils/mixins/button.css
This PR adds a new style for buttons, the _hollow buttons_. They're button with transparent background and colored borders. When hovered, their background changes to a solid color.
> feat(button-hollow): hollow styled buttons

- src/js/components/lazy-load.js
- test/fixture/lazy-load.html
On lazy-load component, when an URL has a trailing comma, for instance `http://some-url.com/cortina1,40x,5,2`, the `parsingBreakpoint` method was splitting the whole string including the URL, resulting in wrongs URLs for the image src.
This PR fixes this behavior by splitting the `data-srcset` using a regex that does not include the URL.
> fix(lazy-load): fix breakpoint parsing when a comma is on data-srcset

- docs/css/glyphs.md
- src/glyphs/order.svg
- src/glyphs/settings.svg
This PR adds glyphs for `settings` and `order`:
> feat(glyphs): add glyphs for order and settings

- src/js/components/collapse.js
- test/components/collapse.spec.js
When using collpase inside a modal, scrollHeight returns 0
> fix(collapse): prevent scrollHeight from being 0

- src/js/components/modal.js
- test/components/modal.spec.js
work with emitter if someone needs to do something when modal show or hide.
> feat(modal): add emit `modal:show/hide` when methods are called

- src/css/atoms/button-hollow.css
The `:focus` state was missing on coloured `button-hollow` elements.
> fix(button-hollow): background color on focus state

- docs/css/form.md
- src/js/components/form.js
- test/components/form.spec.js
- test/fixture/form.html
Before, we were only validating if the **value** was null, but in the case of select field is more honest validate the **textContent** is null to avoid overlap
> fix(form): floating label on select field when selected option is empty

- docs/css/scaffolding.md
The variable `color-black` was missing on scaffolding section.
> docs(scaffolding): add color-black to variables

- src/js/components/modal.js
- test/components/modal.spec.js
It's common to have an anchor as the trigger to open the modal. Sometimes we want to keep its `href` attribute, but we do not want to be redirected. So it would be really nice to prevent the default behavior of this element. This PR does that.
> fix(modal): prevent default behavior when open modal trigger is clicked

- gulpfile.js
- package.json
This PR changes the gulp default task to run the `build` task before `styles:docs` task to avoid possible errors when running the default task for first time.
Also, this PR adds a npm start script as the gulp default task.
> Run styles:docs only after build is finished

- karma.conf.js
- src/js/components/validation.js
- test/components/validation.spec.js
- test/fixture/validation.html
If we have an input with `[data-required]` but it don't have `[data-validate]`, you can't submit a form. 
~~i know that have an input with `[data-required]` and `[data-validate]` don't make sense, but it's better to prevent it :)~~
as you can see, if you have inputs without `[data-validate]`, the mapped array in `validateAll()` will return something like this:
and `every` will always return `false` :(
> feat(validation): filter inputs without [data-validate]

- docs/js/modal.md
- src/js/components/modal.js
- test/components/modal.spec.js
Added booleans options `static` and `keyboard`.
With this options the modal cannot be closed by the user. It's possible to use a modal in cases where a user interaction is mandatory.
When passing true to `static`, the icon `X` to close the modal are not inserted, clicking outside the modal don't close the modal. The default value is `false`.
When passing `false` to `keyboard`, the `esc` key don't close the modal. Default value is `true`.
> feat(static-modal): add options to avoid user to close modal

- src/css/atoms/form/select.css
- src/css/molecules/field.css
The desired behavior for when users click the label within a select tag is to open the select options. That is not a common behavior for selects so in order to achieve that the CSS for the label and the select tag was modified a little bit. Now the label stands behind the select, which has a transparent background. With that, all the clicks, including the ones on a label, will now be registered on the select block.
> feat(select): Open select options on label click

- src/css/molecules/field.css
Ignores the click on the `label` and open the options in the `select` form element.
> feat(select): Open select option on label click

- docs/js/modal.md
- docs/layout/page.jade
- src/css/atoms/modal.css
- src/css/atoms/modal/content.css
- src/js/components/modal.js
- test/components/modal.spec.js
Add a size option to modal component, with three possibilities: small, medium(default value) and large.
Doc:
> feat(modal): Add size option to modal component

- docs/js/alert.md
- docs/layout/page.jade
- src/css/atoms/button.css
- src/js/components/alert.js
- test/components/alert.spec.js
- test/fixture/alert.html
Add the Alert component extends the actual modal component using JQuery plugin.
Alert provides some customizable options such as: textMessage, textButton, size, and triggerClose. 
Docs: 
Alert:
> feat(alert): Add Alert component

- .eslintrc
- docs/js/modal.md
- src/js/components/modal.js
- test/components/modal.spec.js
Esse PR altera o comportamento do back button no browser e no mobile. Quando existir algum modal aberto na página, a ação esperada é que o back button apenas feche o modal e o usuário permaneça na página atual.
> feat(modal): Adjust behaviour for back button and modals

- docs/layout/_partials/github-corner.jade
- docs/layout/index.jade
- docs/layout/page.jade
- docs/styles/organisms/header.css
This will provie an easier way for people to find our repo on GitHub.
> docs(github): Add github corner to docs pages

- src/js/components/tooltip.js
- test/components/tooltip.spec.js
It is impossible, from the outside, to call a method on the popper instance itself, such as `update`, `destroy` and so on. This PR will store the instance in a data-attribute on the tooltip element, so we can access it using `$tooltip.data('popper')`.
> feat(tooltip): Register the Popper instance on the tooltip element

- README.md
- docs/getting-started.md
Add about CDN at getting started documentation.
> docs(getting-started): Add CDN to getting started documentation

- docs/css/form.md
- src/css/atoms/form/select.css
- src/css/molecules/field.css
This PR add `appearance: none` to `.select` inputs, for all devices render a default design.
Before:
After:
> fix(select): added appearance none to .select inputs

- src/css/molecules/field.css
When the text on the `option` tag is big, the arrow was overlapping it.
> fix(forms): Update select arrows to not overlap option text

- docs/components/grid.md
- docs/layout/page.jade
- docs/styles/organisms/docs.css
Add some interactivity to toggle container types in the example for the containers section.
> docs(grid): Improve docs for Grid component page

- docs/components/confirm.md
- docs/layout/page.jade
- src/js/components/confirm.js
- test/components/confirm.spec.js
Add the Confirm component extends the actual modal component using JQuery plugin.
Confirm  receives a callback and provides some customizable options such as: textMessage, textConfirmButton, textCancelButton, and size.
> feat(confirm): Add Confirm component

- docs/components/css-form.md
- docs/components/css-notifications.md
- docs/components/css-utilities.md
- docs/components/js-form.md
- docs/components/js-notifications.md
- docs/components/js-utilities.md
- docs/layout/page.jade
Change `page` layout to apply `link-active` class according to section of the current page as well.
The image below shows all the sections without the unnecessary prefixes `CSS` or `JS`.
> feat(sidebar-labels): Remove prefixes from section names

- src/js/utils/scroll.js
In order to add options to `jump.js` util, add `DEFAULTS` const with base `jumpjs` config and extend to a custom config.
> fix(jump.js): add default options to jump and extends from util option

- docs/components/tooltip.md
- docs/layout/page.jade
- package.json
- src/js/components/tooltip.js
Update Popper.js version and fix tooltip placement bug by adjusting options passed to component constructor.
> fix(popper.js): pass placement options to constructor

- .hound.yml
- package.json
- test/entry.js
Make an instance of `sinon.test` available for all the tests. This was necessary due to the extraction of the `sinon.test` from the Sinon API.
> chore(sinon-test): create instance of sinon.test for tests

- .eslintrc
- package.json
Due to the ESLint update, we're getting "no-unused-expressions" when writing Chai expectations. The [eslint-plugin-chai-friendly](https://github.com/ihordiachenko/eslint-plugin-chai-friendly) overrides the original rule to make it work.
> chore(lint): Add chai friendly eslint plugin

- src/js/components/alert.js
- src/js/components/confirm.js
- test/components/alert.spec.js
- test/components/confirm.spec.js
The focus was still placed on the element that triggered the dialog, causing the opening of multiple dialogs when hitting the `enter` key
> fix(dialogs): Focus on the dialog buttons after displaying an alert or confirm

- src/js/components/collapse.js
This fixes an error thrown by chai-friendly due to a conditional operator in the Collapse component.
> fix(chai-friendly): adjust conditional operator in Collapse component

- .stylelintrc
Fix warning thrown by stylelint on `selector-no-id` rule.
> Update syntax for stylelint rule

- src/css/molecules/field.css
Update the select arrow to have point-events equals none at fields style.
> fix(field): add pointer-events none to select arrow

- src/css/atoms/tooltip.css
> fix(tooltip): add zindex to prevent it for staying behind

- src/css/molecules/pricetag.css
Based on merchandising visual identity, we removed stripes from promotional pricetag
before: 
afeter:
> feat(pricetag): remove stripes from promotional modifier

- src/css/atoms/form/addon.css
- src/css/atoms/form/field.css
Update the addon to have point-events equals none at fields and addon style.
> fix(addon): remove pointer-event from addon

- src/js/components/confirm.js
Buttons inside confirm modal were misaligned only in mobile, but did a small change in grind
> fix(confirm): button alignment grid

- src/css/atoms/form/addon.css
- src/css/atoms/form/field.css
When pointer-events is set to none, is not possible to trigger a click event on the addon glyph.
Revert the PR #264 that set pointer-events to none on addon.
> fix(addon): reverting pointer-events on addon css class

- src/js/utils/trigger-event.js
- test/utils/trigger-event.spec.js
As the constructor we were using before was deprecated, I find it interesting to update it. Also, I needed to pass an event options object as a parameter to this `util`, so I updated that as well.
> refactor(trigger-event): update constructor for Event objects

- src/js/components/modal.js
- test/components/modal.spec.js
On show method, we always emit `modal:show` but in hide method we just emit this event when history feature is enabled. This pr makes hide methodo always emit `modal:hide`
> fix(modal): always emit modal:hide
